server:
  port: 8080
spring:
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000
  application:
    name: project-v
  data:
    mongodb:
      uri: mongodb://localhost:27017/user_data
      auto-index-creation: true